FROM nginx:alpine

# remove default conf
RUN rm -f /etc/nginx/conf.d/default.conf

# add config files
ADD ./config/nginx/nginx.conf /etc/nginx
ADD ./config/nginx/conf.d /etc/nginx/conf.d

# nginx user must own the cache directory to write cache
RUN chown -R 101:0 /var/cache/nginx \
    && chmod -R g+w /var/cache/nginx

EXPOSE 8080

STOPSIGNAL SIGTERM

USER 101

CMD ["nginx", "-g", "daemon off;"]