version: "3"
services:
  service:
    image: reloni/goexample
    container_name: gotest
    networks: 
      backend:
        aliases:
          - weatherapp-back
      frontend:
        aliases:
          - weatherapp-front
  reverseproxy:
    image: nginx:alpine
    container_name: gotest-reverseproxy
    ports:
      - "8080:80"
    networks:
      - backend
      - frontend
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
  redis:
    image: redis:alpine
    container_name: gotest-redis
    networks:
      - backend
networks:
  frontend:
  backend:
    internal: true