FROM reloni/goexample-base

ADD ./src ./src/app
RUN go build -gcflags 'all=-N -l' -i -o $GOPATH/bin/app $GOPATH/src/app

EXPOSE 8080 40000

CMD ["dlv", "debug", "app", "--listen=:40000", "--headless=true", "--api-version=2", "--log"]