FROM golang

ENV CGO_ENABLED 0
ENV GOPATH /go
ENV PATH go/bin:$PATH
WORKDIR $GOPATH

RUN go get "github.com/golang/glog"
RUN go get "github.com/gorilla/mux"
RUN go get "github.com/derekparker/delve/cmd/dlv"