version: "3"
services:
  service:
    image: reloni/goexample:latest
    container_name: gotest
    networks: 
      backend:
        aliases:
          - weatherapp-back
      frontend:
        aliases:
          - weatherapp-front
  reverseproxy:
    image: reloni/goexample-nginx:latest
    container_name: gotest-reverseproxy
    depends_on:
      - service
    ports:
      - "8080:8080"
    networks:
      - backend
      - frontend
  redis:
    image: reloni/goexample-redis:latest
    container_name: gotest-redis
    networks:
      - backend
networks:
  frontend:
  backend:
    internal: true