version: "3"
services:
  service:
    image: reloni/goexample:latest
    container_name: gotest
    deploy:
      mode: global
    networks: 
      frontend:
        aliases:
          - weatherapp-back
  reverseproxy:
    image: reloni/goexample-nginx:latest
    container_name: gotest-reverseproxy
    deploy:
      mode: global
    ports:
      - "8080:8080"
    networks:
      - frontend
  redis:
    image: reloni/goexample-redis:latest
    container_name: gotest-redis
    deploy:
      placement:
        constraints:
          - node.labels.type == main
    networks:
      - frontend
networks:
  frontend:
    driver: overlay
    internal: false