FROM golang:1.13.4-alpine3.10

ENV CGO_ENABLED=0 \
    GOPATH=/go \
    PATH=go/bin:$PATH
WORKDIR $GOPATH

RUN apk add --no-cache git && \
    go get "github.com/gorilla/mux" && \
    go get "github.com/gomodule/redigo/redis" && \
    go get "github.com/derekparker/delve/cmd/dlv"