FROM golang

ENV CGO_ENABLED 0
ENV GOPATH /go
ENV PATH go/bin:$PATH
WORKDIR $GOPATH

ADD ./src ./src/app
RUN go get "github.com/golang/glog"
RUN go get "github.com/gorilla/mux"
RUN go build -gcflags 'all=-N -l' -i -o $GOPATH/bin/app $GOPATH/src/app
RUN go get "github.com/derekparker/delve/cmd/dlv"

EXPOSE 8080 40000

CMD ["dlv", "debug", "app", "--listen=:40000", "--headless=true", "--api-version=2", "--log"]