FROM golang:1.13.4-alpine3.10

ENV CGO_ENABLED 0
ENV GOPATH /go
ENV PATH go/bin:$PATH
WORKDIR $GOPATH

RUN apk add --no-cache git
RUN go get "github.com/gorilla/mux"
RUN go get "github.com/derekparker/delve/cmd/dlv"