apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotest-app-morty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotest-app-morty
  template:
    metadata:
      labels:
        app: gotest-app-morty
    spec:
      containers:
      - image: reloni/goexample
        name: gotest-app-morty
        ports:
        - containerPort: 8080
          protocol: TCP
